// Parola: the "word of the day" list.
// Everyone sees the same word on the same day. Add, remove or reorder words freely:
// one word or expression per string, in its dictionary form (infinitive, singular).
const DAILY_WORDS = [
  "discostare", "sbrigarsi", "magari", "sfizio", "sgomento", "barcamenarsi", "accorgersi", "arrangiarsi",
  "sbadato", "spensierato", "struggente", "ammiccare", "abbagliare", "sfumatura", "incantevole", "stufo",
  "azzeccare", "sgarbato", "pignolo", "sbrogliare", "tergiversare", "rimpiangere", "rincorrere", "scorcio",
  "garbo", "noncuranza", "trascurare", "sfogarsi", "impiccione", "sfacciato", "svogliato", "rilassarsi",
  "girovagare", "zampillare", "sgranocchiare", "abbuffarsi", "spuntino", "pennichella", "sbadigliare", "fannullone",
  "brontolare", "chiacchierare", "sussurrare", "balbettare", "bisbigliare", "strillare", "borbottare", "farfugliare",
  "ingegnarsi", "cavarsela", "rimboccarsi le maniche", "scampare", "sventare", "intralciare", "ostacolare", "agevolare",
  "sfruttare", "sprecare", "risparmiare", "sborsare", "spiccioli", "caparra", "scontrino", "saldi",
  "rovistare", "frugare", "sbirciare", "adocchiare", "scrutare", "intravedere", "scorgere", "avvistare",
  "sfiorare", "accarezzare", "strofinare", "spalmare", "impastare", "mescolare", "sbucciare", "grattugiare",
  "affettare", "soffriggere", "rosolare", "sfornare", "assaggiare", "gustare", "prelibato", "stuzzicare",
  "abbaiare", "miagolare", "ronzare", "cinguettare", "gracidare", "fruscio", "brusio", "rimbombo",
  "tramonto", "crepuscolo", "alba", "afa", "acquazzone", "grandine", "nebbia", "pozzanghera",
  "sentiero", "radura", "ruscello", "scoglio", "insenatura", "anfratto", "vetta", "pendio",
  "incrocio", "marciapiede", "vicolo", "sottopassaggio", "ingorgo", "parcheggiare", "sorpassare", "frenare",
  "traslocare", "scatolone", "inquilino", "affitto", "bolletta", "condominio", "soffitta", "cantina",
  "sbrigativo", "puntuale", "ritardatario", "scadenza", "rimandare", "anticipare", "posticipare", "procrastinare",
  "impegnarsi", "sforzarsi", "cimentarsi", "destreggiarsi", "affrontare", "superare", "arrendersi", "insistere",
  "fidarsi", "diffidare", "sospettare", "ingannare", "illudersi", "deludere", "stupire", "sbalordire",
  "commuoversi", "emozionarsi", "vergognarsi", "offendersi", "arrabbiarsi", "calmarsi", "rassegnarsi", "consolare",
  "nostalgia", "malinconia", "rimorso", "rancore", "gratitudine", "tenerezza", "imbarazzo", "sollievo",
  "coraggio", "pudore", "orgoglio", "invidia", "gelosia", "pazienza", "saggezza", "ingenuità",
  "testardo", "permaloso", "timido", "spiritoso", "premuroso", "generoso", "tirchio", "vanitoso",
  "goffo", "maldestro", "svelto", "sveglio", "furbo", "tonto", "saccente", "modesto",
  "cianfrusaglia", "aggeggio", "marchingegno", "attrezzo", "cacciavite", "chiodo", "spago", "nastro",
  "sgabello", "cassetto", "mensola", "scaffale", "comodino", "divano", "tappeto", "lenzuolo",
  "arrossire", "impallidire", "sussultare", "rabbrividire", "sudare", "starnutire", "tossire", "singhiozzare",
  "zoppicare", "inciampare", "scivolare", "barcollare", "accovacciarsi", "sdraiarsi", "stiracchiarsi", "rannicchiarsi",
  "sbocciare", "appassire", "germogliare", "potare", "innaffiare", "seminare", "raccogliere", "vendemmia",
  "sagra", "festa patronale", "processione", "fuochi d'artificio", "bancarella", "mercatino", "fiera", "presepe",
  "in bocca al lupo", "acqua in bocca", "costare un occhio della testa", "essere al verde", "prendere in giro",
  "fare la scarpetta", "avere le mani in pasta", "non vedere l'ora", "a quattr'occhi", "alla buona",
  "a occhio e croce", "di punto in bianco", "a malincuore", "di sfuggita", "all'improvviso", "a vanvera",
  "d'altronde", "tuttavia", "eppure", "pertanto", "anzi", "infatti", "comunque", "purché",
  "sebbene", "nonostante", "affinché", "qualora", "altrimenti", "perlomeno", "addirittura", "tantomeno",
  "ormai", "tuttora", "finora", "appena", "mica", "pure", "ebbene", "insomma",
  "boh", "dai", "magari", "figurati", "macché", "meno male", "per carità", "ci mancherebbe",
  "sciopero", "bando", "concorso", "graduatoria", "tirocinio", "stipendio", "busta paga", "ferie",
  "colloquio", "curriculum", "scrivania", "riunione", "verbale", "pratica", "sportello", "modulo",
  "abbonamento", "biglietteria", "binario", "coincidenza", "capolinea", "fermata", "pendolare", "sciopero dei trasporti",
  "ritrovo", "comitiva", "brindisi", "cin cin", "aperitivo", "stuzzichino", "digestivo", "ammazzacaffè",
  "sbronza", "brillo", "astemio", "goloso", "buongustaio", "schizzinoso", "ingordo", "sazio",
  "spigliato", "disinvolto", "impacciato", "garbato", "sgarbo", "cortesia", "complimento", "sfottere",
  "baruffa", "bisticciare", "litigare", "fare pace", "chiarire", "fraintendere", "equivoco", "malinteso",
  "sbagliare", "sbaglio", "svista", "strafalcione", "rimediare", "scusarsi", "perdonare", "sdebitarsi",
  "incoraggiare", "rincuorare", "spronare", "scoraggiare", "demoralizzare", "entusiasmare", "annoiare", "stancare"
];
